### ISSUE TITLE
IPF file was deleted when TOS startup

### ISSUE THREAD

**Issue by liiwza** [Xanaxiel/ToS-Addons#12]
Issue:
うtooltiphelper.ipf will be deleted when I run TOS.
The way I did try.

1.Installed the 1.80 tooltip helper by Tree of savior addon manager
Run the game. The ipf is gone.
2. Download the 1.80 tooltip helper from GitHub manually
Run the game. The ipf is gone.

However, other addons are running ok. Strange :(

**Comment by Xanaxiel** [comment]
Yeah it's a problem with the unicode character. Try manually downloading it again, then rename it to `_tooltiphelper-✉-v1.8.0` I'll fix this in a while, will be adding something new.
