### ISSUE TITLE
pet stamina

### ISSUE THREAD

**Issue by Diolik** [Xanaxiel/ToS-Addons#13]
Hello.

Pet stamina didn't update when i mounted... I need unmount and mount, then will refresh.

Sorry for my terrible english.

**Comment by Xanaxiel** [comment]
What version are you using? There's no updates for pet stamina though, still the same old version. Use [this version](https://github.com/Xanaxiel/ToS-Addons/releases/download/v1.9.0/showpetstamina-v1.7.0.ipf)

**Comment by Diolik** [comment]
From addon manager 1.7.0

https://i.gyazo.com/a206bc5c9cac89ab67b500ef37b8a7eb.png

**Comment by Xanaxiel** [comment]
I'm not sure... Works fine for me. Try to update all your addons, there might be a conflict with others on your version.

**Comment by Diolik** [comment]
all addons from addon manager(

hm... install 1 addon "staminapet"... and nothing change(

**Comment by Diolik** [comment]
oh... lkchannel is conflict( when delete this, petstamins is ok) sorry =)

**Comment by Xanaxiel** [comment]
I have no idea, I can't replicate your issue sadly...
