### ISSUE TITLE
After last updates tis addons not working

### ISSUE THREAD

**Issue by smileness** [Xanaxiel/ToS-Addons#14]
Hello,
After tomorrow's updates, this addons not working anymore, please take a look and see if you can fix it :)

Thanks

Best Regards

Smile~

**Comment by Xanaxiel** [comment]
I don't understand? What do you mean by 

> After tomorrow's updates

Works fine for me though, care to elaborate further?

**Comment by smileness** [comment]
Sorry, I mean, yesterday's update

:3

Thanks~

**Comment by Xanaxiel** [comment]
How come it's not working? Could you elaborate more on your issue? 

More details please, what did you do before that? Did you get latest release of [Addon Manager](https://github.com/Excrulon/Tree-of-Savior-Addon-Manager/releases/latest)? Did you read the instructions?
