### ISSUE TITLE
About the necronomicon corpses

### ISSUE THREAD

**Issue by kebobitz** [Xanaxiel/ToS-Addons#15]
After changing maps it doesnt show the corpse bar. It will only show after a corpse is used or a corpse pot is used. 
The necronomicon also needs to be clicked in order to show the corpse bar.  
And when the corpse bar is shown, whenever i use a corpse pot or a skill the corpse bar remain as is.

That's all i encountered so far. Hope it helps in improving it more :+1:

**Comment by Xanaxiel** [comment]
Thanks for the feedback! This greatly helps as I'm really not sure what function to use to update it. Will fix when I get home from work.

**Comment by Xanaxiel** [comment]
Just did a fix, can you test and let me know? Thanks!

**Comment by kebobitz** [comment]
Work like a charm man! Thank you very much for the add on! :+1:

**Comment by Xanaxiel** [comment]
You're welcome!
