### ISSUE TITLE
Ability to toggle which info you want on items?

### ISSUE THREAD

**Issue by HandOfFate** [Xanaxiel/ToS-Addons#17]
I'm just interested in if the item is used in a collection and which recipes they're used in.
Not interested in journal pts/# collected/magum opus results/market or anything else.

Anyway to adjust it to the simpler versions.

**Comment by Xanaxiel** [comment]
Check the config in `\steamapps\common\TreeOfSavior\addons\tooltiphelper\tooltiphelper.json`
