### ISSUE TITLE
Impossible to install/update as of v2.1.2

### ISSUE THREAD

**Issue by allysson-david** [Xanaxiel/ToS-Addons#18]
Hello, first let me thank you for your good work: Thank you! :D

Alright, so here's the problem:
Since you released v2.1.2 it isn't possible to download/update Tooltip Helper.

From what I can see the problem lies in the fact that the **releaseTag** in **addons.json** is **v2.1.2** while the real release tag you used is just **2.1.2** (without the **v**).

In other words...
Expected url by the Addon Manager: https://github.com/Xanaxiel/ToS-Addons/releases/download/v2.1.2/tooltiphelper-v2.1.2.ipf
Current url at GitHub: https://github.com/Xanaxiel/ToS-Addons/releases/download/2.1.2/tooltiphelper-v2.1.2.ipf

**Comment by yotitchy** [comment]
same here, cant we install manually ?

**Comment by Spinner25** [comment]
Same problem here 
![tooltip](https://cloud.githubusercontent.com/assets/22779473/19289345/24a4701c-8fbf-11e6-8278-de0256cf16c8.png)

**Comment by Xanaxiel** [comment]
Just fixed everything I encountered, should be all good by now
