### ISSUE TITLE
additional

### ISSUE THREAD

**Issue by rbelota** [Xanaxiel/ToS-Addons#19]
Hello! First I want to thank the addon Market Filter.
I have some ideas, do not know if any other friend may have given this collaboration.
We have a hard time looking for the hats and even, more easy way, the recipes and blue items, purple or orange.
It is to facilitate this? If you can and put the addon, we would appreciate a lot.
thanks!

**Comment by Xanaxiel** [comment]
I don't quite follow what you're asking. If you're referring to inventory sorting, there's Assortments on the addon manager.

**Comment by rbelota** [comment]
I apologize for not telling which addon. excuses same!
but, then, it is the addon Market Help. Addon great!

In the market, it is difficult to find some items easier. And I see that the market would facilitate this filter

**Comment by Xanaxiel** [comment]
Actually it's still underway, just need the time. If you got some progress feel free to hit up a PR.

**Comment by Xanaxiel** [comment]
Seems I could close this, IMC has already implemented this.
