### ISSUE TITLE
Cant use it with exculdron

### ISSUE THREAD

**Issue by Greedys** [Xanaxiel/ToS-Addons#2]
I copy paste in addonloader.lua the dofile and nothing happen, i cant use it :(

**Comment by Greedys** [comment]
--[[ADDONS]]

dofile("../addons/mapfogviewer/mapfogviewer.lua");
dofile("../addons/monsterframes/monsterframes.lua");
dofile("../addons/monstertracker/monstertracker.lua");
dofile("../addons/tooltiphelper/tooltiphelper.lua");

And the "load addons dont read that"

**Comment by Xanaxiel** [comment]
That's weird, I just tested, as well as hotfixed earlier. Can you download the [latest release](https://github.com/Xanaxiel/ToS-Addons/releases/latest) and try again?

For the latest release the following need to be added:

``` javascript
--previous dofile lines
dofile("../addons/tooltiphelper/tooltiphelper.lua");
dofile("../addons/showpetstamina/showpetstamina.lua")
```

**Comment by Greedys** [comment]
--[[ADDONS]]

dofile("../addons/mapfogviewer/mapfogviewer.lua");
dofile("../addons/monsterframes/monsterframes.lua");
dofile("../addons/monstertracker/monstertracker.lua");
dofile("../addons/tooltiphelper/tooltiphelper.lua");
dofile("../addons/showpetstamina/showpetstamina.lua")

**Comment by Greedys** [comment]
![image](https://cloud.githubusercontent.com/assets/19364005/15271136/45c43cc4-1a11-11e6-883d-e91f33f0ae1f.png)

**Comment by Xanaxiel** [comment]
Need the following info:
What other addons are you using? 
Are you using both Excrulon's and fiote's? Or just one of them?

**Comment by Greedys** [comment]
Just Excrulons

**Comment by Greedys** [comment]
![image](https://cloud.githubusercontent.com/assets/19364005/15271138/6b97c3ee-1a11-11e6-90d2-6159ed79fee8.png)

**Comment by Xanaxiel** [comment]
Did you get his latest release?

**Comment by Greedys** [comment]
![image](https://cloud.githubusercontent.com/assets/19364005/15271140/81b8239e-1a11-11e6-8a18-4c4f4f955675.png)

**Comment by Greedys** [comment]
Mmmm i'm going to delete all and download all the lastest of him

**Comment by Xanaxiel** [comment]
Timestamps on the folder structure look old, [download it first](https://github.com/Excrulon/Tree-of-Savior-Lua-Mods/releases/tag/1.9.1).

**Comment by Greedys** [comment]
Yep, that was the problem, the excruldon was old, thx alote for your time i love your addon

PS: This addon have all the items of the collections??

**Comment by Xanaxiel** [comment]
What do you mean? It indicates if the item is part of the collection, and if you mean by if it references all items then yes. Closing issue.

**Comment by Greedys** [comment]
Okk tyyyy, and the only thing and i stop taking your time

I try to delete some addons (Exp viewer) but i delete the dofile and if i do that, no1 works
