### ISSUE TITLE
Question about Magnus Opus especific iten and update

### ISSUE THREAD

**Issue by Kamashii** [Xanaxiel/ToS-Addons#20]
Hi,
My question is about a especific itens recorded by Magnus Opus.
For exemple, Yekubite Crystal is made by Yekubite Teeh, but no one know how to get Yekubite Teeth, and for this reason no one know if is possible made him by Magnus Opus, we have how know if it is possible? '-'

I saw that all new itens show its collection box, but none show the recipes made from him or possible Magnus Opus, mainly the itens from orange weapons, you plan to upgrade the addon?

Thank you and excuse me any incovenient.

**Comment by Xanaxiel** [comment]
They should show, probably because the game files aren't updated yet.
