### ISSUE TITLE
Latest tooltiphelper commit Whitespace in tooltips

### ISSUE THREAD

**Issue by Navitron** [Xanaxiel/ToS-Addons#4]
Newest tooltiphelper commit introduces lots of whitespace in the tooltips.

![screenshot_20160514_00002](https://cloud.githubusercontent.com/assets/1194994/15271281/46855ec4-19f6-11e6-8be0-a3a91951f6f1.jpg)

**Comment by Xanaxiel** [comment]
Yeah I'm trying to find a way between loaders, will fix in a while.

**Comment by Xanaxiel** [comment]
Should be fixed in latest commit
