### ISSUE TITLE
Regular tooltip not showing, only after hovering other

### ISSUE THREAD

**Issue by bsides** [Xanaxiel/ToS-Addons#6]
While you're seeing an item that have something in the tooltip with this addon (like collection, etc), if you hove an item that doesn't have anything (say, Pine Wood) the regular tooltip just doesn't show. You have to hover out and then go over it again to show. I'm guessing it's a minor issue, but kind of annoying. 

Thanks for the addon btw :+1:

**Comment by Qupu** [comment]
It actually doesnt work on some items that have collections or/and receipts its in.
And Pine Wood actually is in some receipts.

**Comment by Xanaxiel** [comment]
I'll continue fixing/testing after maintenance. I think this issue is caused by "unregistered" collections, and not related to recipes. The game doesn't keep track of the collections which you haven't registered yet, thus gotta have to manually count the prerequisites based off the collection items it has versus just getting it from registered collections.

**Comment by aktai0** [comment]
I noticed that as a workaround you can press 'alt' while hovering over those no-tooltip items and it will show the tooltip in the middle of the screen (Full screen mode in 1920x1080, keyboard mode). I've also noticed that when you hover over one of those items, it makes an empty frame behind the inventory screen (not sure if this helps, but I've attached a screenshot).

![hover frame](https://cloud.githubusercontent.com/assets/5465738/15287492/10b95db8-1b18-11e6-8d91-91ff36ccc147.png)

**Comment by Xanaxiel** [comment]
Will update with a hotfix release, found the issue, just doing another pass.

**Comment by Xanaxiel** [comment]
[Latest release](https://github.com/Xanaxiel/ToS-Addons/releases/latest) should fix this
