### ISSUE TITLE
Load addonns picture stuck after adding lines in addonloader.lua

### ISSUE THREAD

**Issue by devolin182** [Xanaxiel/ToS-Addons#7]
Hi there, thanks for your work, the collection add on is just mind blowing because of the amount of items/mats.

Now heres my issue, I have excrutions latest addon pack installed, which works alright and loads the addons after pressing the button just fine.

After I added the two lines in the instructions my add ons DO load, but the picture/button remains visible in the screen(and ur addon works).  If i remove both lines, it works normal again.

Any suggestions ¿?

**Comment by Xanaxiel** [comment]
Oh hmm, did you get my addons from the [latest release](https://github.com/Xanaxiel/ToS-Addons/releases/latest) as well as from Excrulon's [latest release](https://github.com/Excrulon/Tree-of-Savior-Lua-Mods/releases/latest)? If the addons did load, can you post a screenshot of the chatbox with the list that loaded, as well as a screenshot of your folder structure in the addons folder?
